### ISSUE TITLE
Swift Bond for UiLabel

### ISSUE THREAD

**Issue by soundprombile** [SwiftBond/Bond#24]
I thank you for this wonderful program! It has helped me to solve other programming issues I have been grappling with for three weeks! 

I am attempting a procedure much like the code below, intended to continuously change the title of a button to that of a Dynamic String variable.  I can ```println(myButton.dynTitle.value)``` to the logs, but it will not change the actual title of myButton in the simulator.

I am new to programming, and would greatly appreciate your help.

```
@IBOutlet weak var myButton: UIButton!
var abc = Dynamic<String>("Original Button Title")

abc ->> myButton.dynTitle
abc.value = "Button Title Changed"
```

Many Thanks, Dan

**Comment by srdanrasic** [comment]
Hi Dan,

Looks like there was an issue with `dynTitle` of UIButton. It's fixed now. Please get latest version (v3.1.1).

Thanks for reporting this!

**Comment by andersklenke** [comment]
I don't know why. But I still can't manage to get this to work.


View: 
```Swift
listViewModel.currentStop <->> currentStopButton.dynTitle
```

ViewModel:
```Swift
var currentStop =  Dynamic<String>("Something")
```

Another method in the view model, replaces the Dynamic String, with some other string. But the button is not reflecting the string.

**Comment by srdanrasic** [comment]
A rule of thumb: always declare dynamics as constants - using `let` keyword.

```swift
let currentStop =  Dynamic<String>("Something")
```

Because you should never reassign it, but change its value

```swift
currentStop.value = "Something else"
```

**Comment by andersklenke** [comment]
Thanks @srdanrasic ! I still have a lot to learn. 

It works like a dream now :+1:

**Comment by srdanrasic** [comment]
Glad to hear that :)
