### ISSUE TITLE
Issue with bidirectional bindings in NSTextField

### ISSUE THREAD

**Issue by rnine** [SwiftBond/Bond#68]
I was trying to set a bidirectional binding on a `NSTextField` and I think I have spotted a bug (I am using Xcode 6.3. / Swift 1.2)

This is what I have:

```Swift
@IBOutlet weak var textField: NSTextField!
let backedValue = Dynamic<String>("Moose")

func applicationDidFinishLaunching(aNotification: NSNotification) {
   backedValue <->> textField.dynText
}
```

When the textfield is changed, Bond attempts to trigger `-[Bond.TextFieldDynamicHelper textChanged:]` but it fails with "unrecognized selector sent to instance". After looking at `Bond+NSTextField.swift` I noticed that `textChanged` is declared as private:

> Declarations marked private are not exposed to the Objective-C runtime if not otherwise annotated. IB outlets, IB actions, and Core Data managed properties remain exposed to Objective-C whatever their access level. If you need a private method or property to be callable from Objective-C (such as for an older API that uses a selector-based callback), add the @objc attribute to the declaration explicitly.

Perhaps adding @objc would be a good idea?

**Comment by juandent** [comment]
HI,

I reported this issue a while ago... I think adding @objc attribute makes the most sense since it allows us to keep it private

Regards,
Juan Dent

**Comment by srdanrasic** [comment]
Ok guys, should be fixed in v3.7.3. AppKit support is kind of still unofficial. Feel free to contribute if you need additional extensions.

**Comment by rnine** [comment]
@srdanrasic Unfortunately the changes in v3.7.3 did not fix this issue.

I noticed you added the @objc to the class rather than the private function, hence the situation has not changed (selector is still not recognised.)

```Swift
    @objc private func textChanged(sender: AnyObject?) {
        self.listener?(control?.stringValue ?? "")
    }
```

This, however works as intended :+1:

**Comment by srdanrasic** [comment]
Oh. Well, v3.7.4 is out :)

**Comment by rnine** [comment]
@srdanrasic Great, thank you! :+1:
